### PR TITLE
Graphics icing

### PR DESCRIPTION
**Pull request by dkirkby**
This PR is still in progress and will add some graphics "icing":
 - [x] Significant speedups of `drawTrace2d()` and `drawTrace3d()`.
 - [x] Fix missing baffles in `draw2d()`.
 - [x] Optionally draw lenses with fill color in `draw2d()`
 - [ ] More flexible choice of (x,y,z) -> (u,v) mapping in 2d drawing routines.

### CODE REVIEW

**Comment by dkirkby** [comment]
A new `tests/test_draw.py` benchmarks the drawing routines.  Before:
```
time for initialize = 0.05
time for draw3dtelescope = 0.13
time for draw3drays = 9.55
time for initialize = 0.07
time for draw2dtelescope = 0.05
time for draw2drays = 53.72
```
After:
```
time for initialize = 0.05
time for draw3dtelescope = 0.11
time for draw3drays = 0.43
time for initialize = 0.07
time for draw2dtelescope = 0.06
time for draw2drays = 0.18
```
I am not sure why 2d was slower than 3d before, but they are both significantly faster now.

**Comment by dkirkby** [comment]
I meant to create this as a draft PR, but it looks like you cannot change that after a PR is created.

**Comment by dkirkby** [comment]
I just added an optional "only" arg to `draw2d()` that allows different `Optic` subclasses to be drawn with different styles, e.g.
```
telescope.draw2d(ax, c='b', lw=3, only=(batoid.optic.Mirror, batoid.optic.Detector))
telescope.draw2d(ax, c='g', lw=1, only=batoid.optic.RefractiveInterface)
telescope.draw2d(ax, c='r', lw=2, only=batoid.optic.Baffle)
```
This produces:
demo2d

**Comment by dkirkby** [comment]
Not sure what is going on with the tests, but I don't think it is related to my changes.

**Comment by jmeyers314** [comment]
> Not sure what is going on with the tests, but I don't think it is related to my changes.

I think these are fixed on master now.

**Comment by dkirkby** [comment]
I merged your changes on master, but I still need to comment out `addopts = -n auto` in `setup.cfg` to run the tests locally.  Is `-n` even a `pytest` argument?  I don't see it documented [here](https://docs.pytest.org/en/latest/usage.html).   I guess it configures the number of subprocesses / threads for parallel testing?

**Comment by dkirkby** [comment]
I added optional filling and labeling of lenses, e.g.
```
telescope.draw2d(
    ax, fc='c', alpha=0.2, only=batoid.optic.Lens,
    labelpos=0.65, fontdict={'size': 15, 'color': 'gray', 'weight': 'bold'})
telescope.draw2d(ax, c='k', lw=1, alpha=0.3, only=batoid.optic.RefractiveInterface)
telescope.draw2d(ax, c='b', lw=1, only=batoid.optic.Detector)
```
which produces:
lenses

Some of the spaces between our corrector lenses look more lenslike that the actual lenses, so this helps me at least :-)

**Comment by dkirkby** [comment]
@jmeyers314 I am going to punt on my last TODO item, so this is ready for your review.

**Comment by jmeyers314** [comment]
> I merged your changes on master, but I still need to comment out addopts = -n auto in setup.cfg to run the tests locally. Is -n even a pytest argument? I don't see it documented here. I guess it configures the number of subprocesses / threads for parallel testing?

Yes, it's for parallel testing via the pytest-xdist plugin.  Maybe you need to `pip install -r test_requirements.txt`?

**Comment by dkirkby** [comment]
I just confirmed that `pip install -r test_requirements.txt` fixes the issues I was having.  I guess this step should not be performed by `pip install`, but perhaps could be mentioned in a [CONTRIBUTING.md](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors)?

**Pull request merged**
